#!/usr/bin/env python
# -*- coding: utf-8 -*-
#######################################################################
# Coding: UTF-8, 4 spaces indent, LF line terminator
#######################################################################

from Form import Form
import sys

from PyQt4.Qt import *

app = QApplication( sys.argv )
win = Form()
win.show()
sys.exit( app.exec_() )
