######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 14 19:22:49 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += schedulewidget.h
SOURCES += main.cpp schedulewidget.cpp
