######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 4 22:35:49 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += form.h view.h
FORMS += form.ui
SOURCES += form.cpp main.cpp view.cpp
