######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 5 17:12:10 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui
INCLUDEPATH += . src
QT += sql

# Input
HEADERS += src/cache.h src/mainwindow.h
FORMS += ui/mainwindow.ui
SOURCES += src/cache.cpp src/main.cpp src/mainwindow.cpp
